### ISSUE TITLE
Migration : HO-asylum - Jenkins Template and Generate Python File

### ISSUE THREAD

**Issue by MartynBSpooner** [ONS-OpenData/HO-asylum#1]
Please convert the iPython Notebook to a Python .py file and update the JenkinsFile file to match the new template approach.

**Comment by mikeAdamss** [comment]
I've switched this over to using the Jenkins template and it's bubbled up an error that I _think_ has always been there (the following is just my best guess, ignore/investigate as needed).

if you check this failed jenkins job: https://ci.floop.org.uk/job/GSS_data/job/Migration/job/HO-asylum/105/ there is a test section at the bottom, which highlights the failure.

this particular test is run automatically as part of the new Jenkinsfile template but was **not** part of the old manual created Jenkinsfile. So (at a guess) I suspect it's always been failing and we just didn't know until now.

**Comment by LPerryman** [comment]
Opening new issue for this one
